setup.py
changes to setuptools is causing warnings to non-PEP440 compliant version strings
=> make version PEP440 compliant

colander/__init__.py, colander/tests/test_colander.py
When I was trying to introspect schemas I printed out "missing: \<object object at 0x7fa8787da240>", "missing: \<colander.null>" and "missing: \<colander._drop object at 0x7fa8737e4978>".  The first is supposed to be a colander.required but unfortunately it's just a generic object placeholder.  This PR is to unify colander.required, colander.drop and colander.null.
=> unify `required`, `null`, and `drop`

colander/__init__.py
Reverts Pylons/colander#207
`typ` is not a typo.  That's the actual argument name you pass to the class (for better or worse).
=> Revert "Update __init__.py"

colander/__init__.py, docs/api.rst
I updated the docstring to equal what was in the api.rst and then made it display the docstring.  The end result in the html is the same, but now there's only a single copy of the docs and it's in the source code.
=> remove duplication of documentation

colander/__init__.py
The current docs show
`colander.DateTime(default_tzinfo=<object object at 0x7fef11f71aa0>)`
due to using the `_marker`.  `iso8601` has a `UTC` object that is
an already instatiated version of `iso8601.Utc()` and outputs its
repr as "\<iso8601.Utc>".  This should change the docs to print out:
`colander.DateTime(default_tzinfo=<iso8601.Utc>)`.
=> make default UTC directly

CHANGES.rst, colander/__init__.py, colander/tests/test_colander.py
=> fix String encoding

colander/__init__.py
solves #230 
Judging from comments on #162 it seems like we shouldn't be defaulting a `typ` on SchemaNode as people should be using a subclassed version with `schema_type()` defined instead.
A test case is already in place at `TestSchemaNode.test_ctor_without_type`.
=> Update docs regarding `typ` argument to SchemaNode

CHANGES.rst, colander/__init__.py, colander/tests/test_colander.py
PR #183 and #185 tried to fix this but missed one aspect when
a schemanode is added as a child via class definitions.
This is related to http://stackoverflow.com/questions/23135499/colander-subclassing-schemanode/31212539
The funny thing is the example given in #183 didn't work so I used that as the test case.  ^_^
=> issue with `title` being overwritten when child

CHANGES.rst, colander/__init__.py, colander/tests/test_colander.py, docs/api.rst
This is the opposite of OneOf: it ensures that the supplied value is
none of the choices.
=> New NoneOf validator

CHANGES.rst, colander/__init__.py, colander/tests/test_colander.py
This patch adds `normalize` option (which is `False` by default) to `Decimal` type.  It normalizes the serialized/deserialized result by stripping the rightmost trailing zeros.  For example, `1.23000` becomes normalized to `1.23`.
=> Add normalize option to Decimal type

CHANGES.rst, colander/__init__.py, colander/tests/test_colander.py
To deal with #224.  Sequence/SequenceSchema now supports `null` and `drop` in the same way Mapping does.
=> add `drop` support to `Sequence`

CHANGES.rst, CONTRIBUTORS.txt, colander/__init__.py, docs/api.rst
This allow caller to analise errors from extra fields programmatically.
Without this error type to know which fields treated as "extra" caller
must parse error string.
=> Add new exception ExtraItemsError

CHANGES.rst, CONTRIBUTORS.txt, colander/__init__.py, colander/tests/test_colander.py
- Added optional keyword argument `allow_empty` to `colander.String`
schema type. When True, deserializes an empty string to an
empty string. When False (default), an empty string deserializes to
`colander.null`.
I think this satisfies and supercedes https://github.com/Pylons/colander/pull/146.
=> Allow String type to optionally deserialize empty strings

CONTRIBUTORS.txt, colander/__init__.py, colander/tests/test_colander.py
I'm not sure if this is the best way, but here goes.
When we try to clone a SequenceSchema like this
```python
class Persons(SequenceSchema):
name = SchemaNode(String())
print Persons().clone()
```
or 
```python
Persons = SchemaNode(Sequence(), SchemaNode(String(), name='name'))
print Persons.clone()
```
Everything goes ok, but if we do like this
```python
Persons = SequenceSchema(Sequence(), SchemaNode(String(), name='name'))
print Persons.clone()
```
We have "Sequence schemas must have exactly one child node".
=> Error cloning SequenceSchema

colander/__init__.py
Looking at the documentation, I could not understand which parameter I should use between `msg` and `message`. I had to look at the code to understand.
https://github.com/Pylons/colander/blob/2b8cdb330144f932825bdc9be1500e276a3d047a/colander/__init__.py#L293-L299
I'm adding a note to clarify the documentation.
=> Add note about deprecated parameter in docstring

docs/basics.rst
I was looking at the docs to find a way to reject extra keys in cstructs (found `unknown='raise'!) and the syntax error (missing quote in the example Invalid exceptions) and compact notations (no spaces in dicts) were distracting.
=> Fix missing quotes and make spacing more standard

CONTRIBUTORS.txt, colander/__init__.py, colander/tests/test_colander.py
This allows setting child nodes during binding as on the example:
```python
class MySchema(colander.MappingSchema):
@colander.deferred
def child(node, kw):
return kw.get('child')
MySchema().bind(child=colander.SchemaNode(colander.Integer()))
MySchema().bind(child=colander.SchemaNode(colander.String()))
```
The use case for this is where you have a complex nested schema with a small mutable part and you want to update this small part without having to declare another schema.
=> Add support for deferred schema nodes

colander/__init__.py
The same documentation exists here http://docs.pylonsproject.org/projects/colander/en/latest/basics.html#schema-node-objects but I think it's useful to have it with the rest of attributes under `SchemaNode` documentation.
=> added 'insert_before' documentation to 'SchemaNode'

colander/__init__.py, colander/tests/test_colander.py
Fixes #287 
GlobalObjects can now serialize classes as well as modules into absolute import paths.
=> GlobalObject patched serialization

colander/__init__.py, colander/tests/test_colander.py
This avoids keeping a reference, which leads to odd behaviors. Calling
serialize() on an object, one would expect the dictionary to not have
any reference to the original object.
=> Copy the mapping values when serializing.

CONTRIBUTORS.txt, colander/__init__.py, colander/tests/test_colander.py
Some external entities require you to serialize/deserialize dates and datetimes in custom formats.
For instance Systempay (the online payment platform of a French Bank) requires that [datetimes](https://paiement.systempay.fr/html/Doc/Payment_Form/en/Implementation_Guide_Interface_Payment_gateway_Systempay_v3.20.pdf) are given in 'YYYYDDHHMMSS'; without the '-' of the ISO.
=> Serialize/deserialize dates and datetimes with custom formats.

.flake8, .gitignore, .travis.yml, CHANGES.rst, CONTRIBUTORS.txt, MANIFEST.in, colander/__init__.py, colander/compat.py, colander/interfaces.py, colander/tests/test_colander.py, colander/tests/test_interfaces.py, pyproject.toml, setup.cfg, setup.py, tox.ini
Python code of ``colander`` formatted to conform to the PEP 8 style guide.
Added some linters (``flake8`` and ``setup.py check``) into ``tox.ini``.
=> Format Python code of colander to conform to the PEP 8 style guide.

colander/__init__.py, colander/tests/test_colander.py
Actually, it is impossible to manage microseconds using Time SchemaType:
```
>>> from colander import Time
>>> from colander import SchemaNode
>>> from datetime import time
>>> node = SchemaNode(Time())
>>> node.deserialize('10:42:42.424242')
...
colander.Invalid: {'': 'Invalid time'}
>>> t = time(10,42,42,424242)
>>> node.serialize(t)
'10:42:42'
```
This PR handle full ISO format HH:MM[:SS[.mmmmmm]] for deserialization and HH:MM:SS[.mmmmmm] for serialization through time.isoformat.
=> Handle microseconds in Time SchemaType

CHANGES.rst, colander/__init__.py, colander/tests/test_colander.py
This changes the Regex used for validating emails addresses to match the WhatWG HTML spec: https://html.spec.whatwg.org/multipage/input.html#e-mail-state-(type=email)
The same validator is used by browsers for the `<input type="email">` validation.
Closes #283
=> Fix: email regex

CHANGES.rst, colander/__init__.py, colander/tests/test_colander.py
This fixes the URL validator issue reported in #290.
As a side note, this can lead to anyone using this validator and for example deform to be vulnerable to a Denial of Service, since it basically sends Python into an infinite loop. We should back port as necessary, and or notify this as a security issue. 
Closes #290
=> Fix: url validator

CHANGES.rst, colander/__init__.py, colander/tests/test_colander.py
This would disallow float's from being accepted and truncated.
Closes #292
=> Feature: Add a strict mode to Integer

docs/glossary.rst
Adjust the article to match English grammar.
=> Fix typo in glossary.rst

colander/tests/test_colander.py
There is a small typo in colander/tests/test_colander.py.
Should read `goes` rather than `goos`.
=> docs: Fix simple typo, goos -> goes

CHANGES.rst, CONTRIBUTORS.txt, src/colander/__init__.py, tests/test_colander.py
This pull request addresses issue #337 which I raised yesterday. 
I decided against the optional flag to force a cast to type string in case the format was defined.
As always any feedback more than welcomed
=> Deseralize date and datetime inputs

CHANGES.rst, CONTRIBUTORS.txt, src/colander/__init__.py, tests/test_colander.py
After binding, deferred nodes currently are always appended to the end of the list of node children, and named according to their attribute name. This change sends those nodes through the same logic currently implemented in `_add_node_children` so that they can be ordered and named appropriately.
It does this by breaking out the logic inside the loop in `_add_node_children` into its own function -- `_add_node_child` -- to keep the rest of the logic as close to the original as possible, and allowing individual children to be added. If it is preferable to keep helper functions to a minimum, I could modify this to accomplish the same task using only `_add_node_children` and passing the deferred nodes in with a list.
This only allows node arguments such as `insert_before` to affect the …
=> Correct insert_before functionality for deferred nodes

docs/manipulation.rst, src/colander/__init__.py
There are small typos in:
- docs/manipulation.rst
- src/colander/__init__.py
Fixes:
- Should read `exception` rather than `exeption`.
- Should read `colander` rather than `colandar`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

CONTRIBUTORS.txt, docs/api.rst, src/colander/__init__.py, tests/test_colander.py
Closes #347 
As discussed in the linked issue, here’s a first stab at the `DataURL` validator. Locally I added `py39` and `py310` to 
https://github.com/Pylons/colander/blob/048fb24eeb6c3df21831413943dbf89d7b5776e4/tox.ini#L5
and perhaps that should also be added to the Github Actions (see PR https://github.com/Pylons/colander/pull/349)? I’ve not added translations to the locales.
**Question**: perhaps pass three `msg` args to the constructor for the three different errors; or raise just one error message for _all_ cases?
=> Add DataURL validator

src/colander/__init__.py
Fix `instantiate` class decorator docstring typo
=> Fix instantiate decorator docstring typo

docs/basics.rst
```
$ python --version
Python 3.9.18
$ pip freeze | grep colander
colander==2.0
```
=> Update Multiple inheritance in basics.rst

.github/workflows/ci-tests.yml, .readthedocs.yaml, MANIFEST.in, src/colander/__init__.py
See: https://peps.python.org/pep-0257/#multi-line-docstrings
Break argument descriptions into separate chunks, and make them more direct.
Also, remove a Python2 compatibility fossil.
=> docs: conform docstrings to PEP257
